kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8090
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd artifacts/python-backend && PORT=8090 python run.py"

[services.production]

[services.production.run]
args = ["python", "artifacts/python-backend/run.py"]

[services.production.run.env]
PORT = "8090"

[services.production.health.startup]
path = "/api/healthz"
