kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8090
name = "API Server"
paths = ["/api"]

[services.development]
run = "bash -c 'cd /home/runner/workspace/artifacts/python-backend && PORT=8090 python run.py'"

[services.production]

[services.production.run]
args = ["bash", "-c", "cd /home/runner/workspace/artifacts/python-backend && PORT=8090 python run.py"]

[services.production.health.startup]
path = "/api/healthz"
