kind = "web"
previewPath = "/"
title = "Stock Market Frontend"
version = "1.0.0"
id = "artifacts/stock-market-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 3002

[services.development]
run = "BASE_PATH=/ PORT=3002 pnpm --filter @workspace/nestjs-backend-placeholder run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nestjs-backend-placeholder", "run", "build" ]
publicDir = "artifacts/nestjs-backend-placeholder/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "3002"
BASE_PATH = "/"
